url: https://wattersons.us
baseurl: /

# Site settings
title: Home Remodel
email: nope@nope.com
description: "This is the home of our new home remodel blog.  Follow along for the fails."


# Team names, titles and social links
people:
- name: Dallas Watterson
  pic: 1
  position: A Geek.
  social:
    - title: twitter
      url: http://twitter.com/_dwatty
    - title: github
      url: http://github.com/dwatty

- name: Erica Watterson
  pic: 2
  position: Not a Geek.
  social:
    

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/_dwatty
  - title: github
    url: http://github.com/dwatty

# Postal address (add as many lines as necessary)
address:
  - line: Home
  - line: Fisher, IL 61843

# Build settings
markdown: kramdown
permalink: pretty